"""
ComplyFlow — Enterprise Compliance Report Export Service

Generates deterministic, point-in-time compliance reports in PDF and JSON formats
from immutable verification snapshots. Clearly distinguishes AI findings from
human auditor overrides and preserves complete evidence provenance.
"""
from __future__ import annotations

import io
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from fastapi import HTTPException
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.services.delta_service import get_delta_engine
from app.services.file_utils import sanitize_filename
from app.services.storage import StorageInterface, get_storage


class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args: Any, **kwargs: Any):
        super().__init__(*args, **kwargs)
        self._saved_page_states: List[Dict[str, Any]] = []

    def showPage(self) -> None:
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int) -> None:
        self.saveState()
        page_w, page_h = letter
        margin = 36

        if self._pageNumber > 1:
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(colors.HexColor("#475569"))
            self.drawString(margin, page_h - 26, "COMPLYFLOW")
            self.setFont("Helvetica", 8)
            self.setFillColor(colors.HexColor("#94a3b8"))
            self.drawString(margin + 68, page_h - 26, "• Enterprise Compliance Audit Report")
            self.setStrokeColor(colors.HexColor("#cbd5e1"))
            self.setLineWidth(0.5)
            self.line(margin, page_h - 30, page_w - margin, page_h - 30)

        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(margin, 30, page_w - margin, 30)

        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        self.drawString(margin, 18, "Confidential • Generated by ComplyFlow Autonomous AI Compliance Agent")

        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(page_w - margin, 18, page_str)
        self.restoreState()


class ReportService:
    def __init__(self, storage: Optional[StorageInterface] = None):
        self._storage = storage
        self.delta_engine = get_delta_engine()

    @property
    def storage(self) -> StorageInterface:
        return self._storage or get_storage()

    @storage.setter
    def storage(self, value: Optional[StorageInterface]):
        self._storage = value

    async def build_report_data(self, project_id: str, run_id: str) -> Dict[str, Any]:
        project = await self.storage.get_project(project_id)

        if not project:
            raise HTTPException(status_code=404, detail=f"Project '{project_id}' not found")

        target_run = await self.storage.get_verification_run(project_id, run_id)
        if not target_run:
            raise HTTPException(
                status_code=404,
                detail=f"Verification run '{run_id}' not found for project '{project_id}'"
            )

        run_proj_id = target_run.get("project_id")
        if run_proj_id and run_proj_id != project_id:
            raise HTTPException(
                status_code=404,
                detail=f"Verification run '{run_id}' does not belong to project '{project_id}'"
            )

        all_runs = await self.storage.list_verification_runs(project_id)
        target_idx = None
        for idx, r in enumerate(all_runs):
            if r.get("run_id") == run_id or str(r.get("run_number")) == str(run_id):
                target_idx = idx
                break

        predecessor_delta: Optional[Dict[str, Any]] = None
        if target_idx is not None and target_idx > 0:
            pred_run = all_runs[target_idx - 1]
            delta_obj = self.delta_engine.calculate_delta(pred_run, target_run)
            predecessor_delta = delta_obj.model_dump()

        overrides_list = await self.storage.list_auditor_overrides(project_id)
        notes_list = await self.storage.list_auditor_notes(project_id)

        overrides_by_req: Dict[str, Dict[str, Any]] = {
            o["requirement_id"]: o for o in overrides_list if "requirement_id" in o
        }
        notes_by_req: Dict[str, List[Dict[str, Any]]] = {}
        for n in notes_list:
            req_id = n.get("requirement_id", "")
            if req_id:
                notes_by_req.setdefault(req_id, []).append(n)

        reqs_snapshot = target_run.get("requirements_snapshot", []) or []
        matches_snapshot = target_run.get("matches_snapshot", []) or []
        tasks_snapshot = target_run.get("tasks_snapshot", []) or []
        docs_used = target_run.get("documents_used", []) or []

        matches_by_req: Dict[str, Dict[str, Any]] = {
            m.get("requirement_id", ""): m for m in matches_snapshot if m.get("requirement_id")
        }

        requirements_findings: List[Dict[str, Any]] = []
        conflicts_summary: List[Dict[str, Any]] = []

        total_count = len(reqs_snapshot) if reqs_snapshot else len(matches_snapshot)
        sat_count = 0
        miss_count = 0
        conf_count = 0
        part_count = 0

        all_req_ids = [r.get("requirement_id") for r in reqs_snapshot if r.get("requirement_id")]
        for m in matches_snapshot:
            mid = m.get("requirement_id")
            if mid and mid not in all_req_ids:
                all_req_ids.append(mid)

        for req_id in all_req_ids:
            req_meta = next((r for r in reqs_snapshot if r.get("requirement_id") == req_id), {})
            match_data = matches_by_req.get(req_id, {})
            override = overrides_by_req.get(req_id)
            req_notes = notes_by_req.get(req_id, [])

            ai_status = (match_data.get("status") or req_meta.get("status") or "UNKNOWN").upper()
            confidence = match_data.get("confidence", 0.0)
            reasoning = match_data.get("reasoning", "")
            priority = req_meta.get("priority", "MEDIUM")
            title = req_meta.get("title") or match_data.get("requirement_title") or req_id
            description = req_meta.get("description", "")
            required_evidence = req_meta.get("required_evidence", "")
            source_reference = req_meta.get("source_reference", "")

            evidence_raw = match_data.get("evidence", []) or []
            citations = []
            for ev in evidence_raw:
                doc_name = sanitize_filename(ev.get("document_name", "unknown"))
                citations.append({
                    "document_name": doc_name,
                    "page_number": ev.get("page_number"),
                    "section": ev.get("section"),
                    "chunk_id": ev.get("chunk_id"),
                    "quote": ev.get("quote", ""),
                    "relevance": ev.get("relevance", ""),
                    "verified": ev.get("verified", True),
                })

            conflict_details = match_data.get("conflict_detail") or match_data.get("conflict_details")
            if conflict_details:
                conflicts_summary.append(conflict_details)

            if ai_status == "SATISFIED":
                sat_count += 1
            elif ai_status == "MISSING":
                miss_count += 1
            elif ai_status == "CONFLICT":
                conf_count += 1
            elif ai_status == "PARTIAL":
                part_count += 1

            finding_item: Dict[str, Any] = {
                "requirement_id": req_id,
                "title": title,
                "description": description,
                "priority": priority,
                "required_evidence": required_evidence,
                "source_reference": source_reference,
                "ai_status": ai_status,
                "confidence": confidence,
                "reasoning": reasoning,
                "evidence_citations": citations,
                "conflict_details": conflict_details,
                "auditor_override": {
                    "override_id": override.get("override_id"),
                    "original_ai_status": override.get("original_ai_status"),
                    "overridden_status": override.get("overridden_status"),
                    "auditor_reason": override.get("auditor_reason"),
                    "auditor_note": override.get("auditor_note", ""),
                    "updated_at": override.get("updated_at") or override.get("created_at"),
                } if override else None,
                "auditor_notes": [
                    {
                        "note_id": n.get("note_id"),
                        "note_text": n.get("note_text"),
                        "created_at": n.get("created_at"),
                    }
                    for n in req_notes
                ],
            }
            requirements_findings.append(finding_item)

        ai_score = float(target_run.get("compliance_score", 0.0))
        ai_status = target_run.get("overall_status", "ACTION_REQUIRED")

        auditor_adjusted_score: Optional[float] = None
        auditor_adjusted_status: Optional[str] = None

        if overrides_by_req and total_count > 0:
            adjusted_satisfied = 0
            for item in requirements_findings:
                effective_status = item["ai_status"]
                if item["auditor_override"]:
                    effective_status = item["auditor_override"]["overridden_status"]
                if effective_status == "SATISFIED":
                    adjusted_satisfied += 1

            auditor_adjusted_score = round((adjusted_satisfied / total_count) * 100, 1)
            auditor_adjusted_status = "READY" if auditor_adjusted_score == 100.0 else "ACTION_REQUIRED"

        # 8. Fetch Audit Trail up to this run's timestamp
        run_ts = target_run.get("timestamp")
        audit_events = await self.storage.list_audit_events(
            project_id,
            to_timestamp=run_ts,
            limit=50,
        )

        clean_docs = [sanitize_filename(d) for d in docs_used]

        report_data = {
            "report_metadata": {
                "project_id": project_id,
                "project_name": project.get("name", "Untitled Project"),
                "run_id": target_run.get("run_id", run_id),
                "run_number": target_run.get("run_number", 1),
                "run_timestamp": target_run.get("timestamp"),
                "run_trigger": target_run.get("trigger", "INITIAL_ANALYSIS"),
                "framework_id": target_run.get("framework_id"),
                "framework_name": target_run.get("framework_name", "Compliance Standard"),
                "framework_version": target_run.get("framework_version", "1.0"),
                "report_generated_at": datetime.now(timezone.utc).isoformat(),
                "report_version": "1.0",
            },

            "executive_summary": {
                "ai_score": ai_score,
                "ai_status": ai_status,
                "has_auditor_overrides": bool(overrides_by_req),
                "auditor_adjusted_score": auditor_adjusted_score,
                "auditor_adjusted_status": auditor_adjusted_status,
                "total_requirements": total_count,
                "satisfied_count": sat_count,
                "missing_count": miss_count,
                "conflict_count": conf_count,
                "partial_count": part_count,
                "summary": target_run.get("summary", ""),
                "documents_used": clean_docs,
            },
            "predecessor_delta": predecessor_delta,
            "requirements_findings": requirements_findings,
            "conflicts_summary": conflicts_summary,
            "auditor_governance": {
                "total_overrides": len(overrides_list),
                "overrides": [
                    {k: v for k, v in o.items() if k != "stored_filename"}
                    for o in overrides_list
                ],
                "notes": notes_list,
            },
            "remediation_plan": tasks_snapshot,
            "audit_trail": audit_events,
        }
        return report_data


    def generate_pdf(self, report_data: Dict[str, Any]) -> bytes:
        buffer = io.BytesIO()
        margin = 36
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=margin,
            rightMargin=margin,
            topMargin=44,
            bottomMargin=44,
        )

        styles = self._build_styles()
        story: List[Any] = []

        meta = report_data.get("report_metadata", {})
        summary = report_data.get("executive_summary", {})
        delta = report_data.get("predecessor_delta")
        findings = report_data.get("requirements_findings", [])
        conflicts = report_data.get("conflicts_summary", [])
        governance = report_data.get("auditor_governance", {})
        remediation_tasks = report_data.get("remediation_plan", [])

        story.append(Paragraph("COMPLYFLOW", styles["BrandTitle"]))
        story.append(Paragraph("Enterprise Compliance & Verification Audit Report", styles["ReportSubtitle"]))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#2563eb"), spaceAfter=12))

        run_num = meta.get("run_number", 1)
        run_id = meta.get("run_id", f"run_{run_num}")
        proj_name = meta.get("project_name", "Untitled Project")
        proj_id = meta.get("project_id", "")
        run_time = self._format_date(meta.get("run_timestamp"))
        gen_time = self._format_date(meta.get("report_generated_at"))
        trigger = meta.get("run_trigger", "INITIAL_ANALYSIS").replace("_", " ")

        meta_table_data = [
            [
                Paragraph("<b>Project:</b>", styles["MetaKey"]),
                Paragraph(f"{proj_name} <font color='#64748b'>({proj_id})</font>", styles["MetaVal"]),
                Paragraph("<b>Verification Run:</b>", styles["MetaKey"]),
                Paragraph(f"<b>{run_id.upper()}</b> (Run #{run_num})", styles["MetaVal"]),
            ],
            [
                Paragraph("<b>Audit Trigger:</b>", styles["MetaKey"]),
                Paragraph(f"{trigger}", styles["MetaVal"]),
                Paragraph("<b>Run Timestamp:</b>", styles["MetaKey"]),
                Paragraph(f"{run_time}", styles["MetaVal"]),
            ],
            [
                Paragraph("<b>Report Date:</b>", styles["MetaKey"]),
                Paragraph(f"{gen_time}", styles["MetaVal"]),
                Paragraph("<b>Governance:</b>", styles["MetaKey"]),
                Paragraph("Auditor Overrides Active" if summary.get("has_auditor_overrides") else "AI Automated Baseline", styles["MetaVal"]),
            ],
        ]

        meta_table = Table(meta_table_data, colWidths=[1.1 * inch, 2.5 * inch, 1.2 * inch, 2.7 * inch])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#f1f5f9")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 14))

        story.append(Paragraph("1. Executive Summary & Compliance Verdict", styles["SectionHeader"]))

        ai_score = summary.get("ai_score", 0.0)
        ai_status = summary.get("ai_status", "ACTION_REQUIRED")
        has_overrides = summary.get("has_auditor_overrides", False)
        adj_score = summary.get("auditor_adjusted_score")
        adj_status = summary.get("auditor_adjusted_status")

        is_ready = (adj_status == "READY" if has_overrides and adj_status else ai_status == "READY")
        verdict_color = "#059669" if is_ready else "#d97706"
        verdict_bg = "#ecfdf5" if is_ready else "#fffbeb"
        verdict_text = "READY TO SUBMIT" if is_ready else "ACTION REQUIRED"

        if has_overrides and adj_score is not None:
            score_summary_html = (
                f"<b>AI Automated Score:</b> {ai_score}% ({ai_status})<br/>"
                f"<b>Auditor-Adjusted Score:</b> <font color='#059669'><b>{adj_score}%</b></font> ({adj_status})<br/>"
                f"<font color='#64748b' size='8'>* Human auditor overrides applied to AI determinations.</font>"
            )
        else:
            score_summary_html = (
                f"<b>Overall Compliance Score:</b> <font color='{verdict_color}'><b>{ai_score}%</b></font><br/>"
                f"<b>Automated AI Verdict:</b> {ai_status}"
            )

        verdict_table_data = [
            [
                Paragraph(f"<font color='{verdict_color}'><b>{verdict_text}</b></font>", styles["VerdictBox"]),
                Paragraph(score_summary_html, styles["NormalSmall"]),
                Paragraph(
                    f"<b>Satisfied:</b> {summary.get('satisfied_count', 0)} / {summary.get('total_requirements', 0)}<br/>"
                    f"<b>Missing:</b> {summary.get('missing_count', 0)}<br/>"
                    f"<b>Conflicts:</b> {summary.get('conflict_count', 0)}",
                    styles["NormalSmall"],
                ),
            ]
        ]
        verdict_table = Table(verdict_table_data, colWidths=[2.2 * inch, 3.2 * inch, 2.1 * inch])
        verdict_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(verdict_bg)),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor(verdict_color)),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(verdict_table)
        story.append(Spacer(1, 8))

        if summary.get("summary"):
            story.append(Paragraph(f"<b>Audit Overview:</b> {summary.get('summary')}", styles["NormalSmall"]))
            story.append(Spacer(1, 10))

        if delta:
            story.append(Paragraph("2. Verification Run Progression & Comparative Delta", styles["SectionHeader"]))
            delta_summary_text = delta.get("summary", "")
            score_diff = delta.get("score_diff", 0.0)
            diff_sign = "+" if score_diff > 0 else ""

            delta_table_data = [
                [
                    Paragraph("<b>Predecessor Run:</b>", styles["MetaKey"]),
                    Paragraph(f"Run #{delta.get('from_run_number', 1)} ({delta.get('from_run_id', 'run_1')})", styles["MetaVal"]),
                    Paragraph("<b>Score Shift:</b>", styles["MetaKey"]),
                    Paragraph(f"{delta.get('score_before', 0)}% → {delta.get('score_after', 0)}% (<b>{diff_sign}{score_diff}%</b>)", styles["MetaVal"]),
                ],
                [
                    Paragraph("<b>Status Shift:</b>", styles["MetaKey"]),
                    Paragraph(f"{delta.get('status_before')} → <b>{delta.get('status_after')}</b>", styles["MetaVal"]),
                    Paragraph("<b>Resolved Gaps:</b>", styles["MetaKey"]),
                    Paragraph(f"{delta.get('resolved_count', 0)} requirement(s) resolved", styles["MetaVal"]),
                ],
            ]
            delta_table = Table(delta_table_data, colWidths=[1.3 * inch, 2.4 * inch, 1.3 * inch, 2.5 * inch])
            delta_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0fdf4")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#86efac")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dcfce7")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(delta_table)
            if delta_summary_text:
                story.append(Spacer(1, 4))
                story.append(Paragraph(f"<i>{delta_summary_text}</i>", styles["MutedNote"]))
            story.append(Spacer(1, 12))

        sec_num = "3" if delta else "2"
        story.append(Paragraph(f"{sec_num}. Requirement-Level Audit Findings & Grounded Evidence", styles["SectionHeader"]))
        story.append(Paragraph(
            "Every requirement is evaluated against uploaded evidence. Citations contain exact verified verbatim quotes.",
            styles["MutedNote"]
        ))
        story.append(Spacer(1, 6))

        for req in findings:
            story.append(self._render_requirement_card(req, styles))
            story.append(Spacer(1, 8))

        if conflicts:
            sec_num = str(int(sec_num) + 1)
            story.append(KeepTogether([
                Paragraph(f"{sec_num}. Fact-Level Document Contradictions", styles["SectionHeader"]),
                Paragraph("Detailed side-by-side comparison of contradictory factual assertions found across evidence documents.", styles["MutedNote"]),
                Spacer(1, 6),
            ]))

            for conf in conflicts:
                story.append(self._render_conflict_card(conf, styles))
                story.append(Spacer(1, 8))

        overrides_data = governance.get("overrides", [])
        if overrides_data:
            sec_num = str(int(sec_num) + 1)
            story.append(KeepTogether([
                Paragraph(f"{sec_num}. Human Auditor Overrides & Governance Log", styles["SectionHeader"]),
                Paragraph("Record of auditor human-in-the-loop decisions modifying AI automated determinations.", styles["MutedNote"]),
                Spacer(1, 6),
            ]))

            gov_rows = [
                [
                    Paragraph("<b>Requirement</b>", styles["TableHead"]),
                    Paragraph("<b>Original AI</b>", styles["TableHead"]),
                    Paragraph("<b>Auditor Status</b>", styles["TableHead"]),
                    Paragraph("<b>Auditor Justification & Notes</b>", styles["TableHead"]),
                ]
            ]
            for ov in overrides_data:
                orig = ov.get("original_ai_status", "UNKNOWN")
                overridden = ov.get("overridden_status", "SATISFIED")
                reason = ov.get("auditor_reason", "")
                note = ov.get("auditor_note", "")
                justification = f"<b>Reason:</b> {reason}"
                if note:
                    justification += f"<br/><b>Note:</b> {note}"

                gov_rows.append([
                    Paragraph(f"<b>{ov.get('requirement_id')}</b>", styles["NormalSmall"]),
                    Paragraph(orig, styles["NormalSmall"]),
                    Paragraph(f"<font color='#059669'><b>{overridden}</b></font>", styles["NormalSmall"]),
                    Paragraph(justification, styles["NormalSmall"]),
                ])

            gov_table = Table(gov_rows, colWidths=[1.2 * inch, 1.1 * inch, 1.2 * inch, 4.0 * inch])
            gov_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(gov_table)
            story.append(Spacer(1, 12))

        if remediation_tasks:
            sec_num = str(int(sec_num) + 1)
            story.append(KeepTogether([
                Paragraph(f"{sec_num}. Prioritized Remediation Action Plan", styles["SectionHeader"]),
                Paragraph("Specific remediation steps required to achieve compliance readiness.", styles["MutedNote"]),
                Spacer(1, 6),
            ]))

            task_rows = [
                [
                    Paragraph("<b>Task ID</b>", styles["TableHead"]),
                    Paragraph("<b>Severity</b>", styles["TableHead"]),
                    Paragraph("<b>Action Required</b>", styles["TableHead"]),
                    Paragraph("<b>Status</b>", styles["TableHead"]),
                ]
            ]
            for t in remediation_tasks:
                task_id = t.get("task_id", "")
                sev = t.get("severity", "MEDIUM")
                title = t.get("title", "")
                req_act = t.get("required_action") or t.get("description", "")
                status = t.get("status", "OPEN")

                sev_color = "#dc2626" if sev == "CRITICAL" else ("#ea580c" if sev == "HIGH" else "#d97706")
                task_body = f"<b>{title}</b><br/><font color='#475569'>{req_act}</font>"
                if t.get("related_requirement_id"):
                    task_body += f"<br/><font color='#64748b' size='7.5'>Related: {t.get('related_requirement_id')}</font>"

                task_rows.append([
                    Paragraph(f"<b>{task_id}</b>", styles["NormalSmall"]),
                    Paragraph(f"<font color='{sev_color}'><b>{sev}</b></font>", styles["NormalSmall"]),
                    Paragraph(task_body, styles["NormalSmall"]),
                    Paragraph(status, styles["NormalSmall"]),
                ])

            task_table = Table(task_rows, colWidths=[1.1 * inch, 1.0 * inch, 4.4 * inch, 1.0 * inch])
            task_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(task_table)
            story.append(Spacer(1, 12))

        # ── 8. Audit Activity Trail ───────────────────────────
        audit_trail = report_data.get("audit_trail", [])
        if audit_trail:
            sec_num = str(int(sec_num) + 1)
            story.append(KeepTogether([
                Paragraph(f"{sec_num}. Historical Audit Activity Trail", styles["SectionHeader"]),
                Paragraph("Chronological immutable record of compliance actions up to this snapshot:", styles["MutedNote"]),
                Spacer(1, 6),
            ]))

            audit_rows = [
                [
                    Paragraph("<b>Timestamp</b>", styles["TableHead"]),
                    Paragraph("<b>Actor</b>", styles["TableHead"]),
                    Paragraph("<b>Event Type</b>", styles["TableHead"]),
                    Paragraph("<b>Summary & Context</b>", styles["TableHead"]),
                ]
            ]
            # Show in chronological order for the report (earliest to latest up to snapshot)
            chrono_events = sorted(audit_trail, key=lambda e: e.get("timestamp", ""))
            for ev in chrono_events[-20:]:  # Last 20 actions up to snapshot
                ts_str = self._format_date(ev.get("timestamp"))
                actor = ev.get("actor_type", "SYSTEM")
                etype = ev.get("event_type", "").replace("_", " ")
                summ = ev.get("summary", "")
                if ev.get("requirement_id"):
                    summ += f" <font color='#64748b' size='7.5'>[Ref: {ev.get('requirement_id')}]</font>"

                actor_color = "#059669" if actor == "AUDITOR" else ("#2563eb" if actor == "AI_AGENT" else "#475569")

                audit_rows.append([
                    Paragraph(f"<font size='7.5'>{ts_str}</font>", styles["NormalSmall"]),
                    Paragraph(f"<font color='{actor_color}'><b>{actor}</b></font>", styles["NormalSmall"]),
                    Paragraph(f"<b>{etype}</b>", styles["NormalSmall"]),
                    Paragraph(summ, styles["NormalSmall"]),
                ])

            audit_table = Table(audit_rows, colWidths=[1.4 * inch, 1.0 * inch, 1.8 * inch, 3.3 * inch])
            audit_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(audit_table)
            story.append(Spacer(1, 12))

        # ── 9. Documents Inspected & Provenance ────────────────
        clean_docs = summary.get("documents_used", [])
        if clean_docs:
            sec_num = str(int(sec_num) + 1)
            story.append(KeepTogether([
                Paragraph(f"{sec_num}. Inspected Evidence Artifacts & Provenance", styles["SectionHeader"]),
                Paragraph("Files ingested and analyzed as ground-truth evidence for this verification snapshot:", styles["MutedNote"]),
                Spacer(1, 4),
            ]))
            doc_items_html = " • ".join([f"<code>{d}</code>" for d in clean_docs])
            story.append(Paragraph(doc_items_html, styles["NormalSmall"]))

        doc.build(story, canvasmaker=NumberedCanvas)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes


    def _render_requirement_card(self, req: Dict[str, Any], styles: Dict[str, ParagraphStyle]) -> Table:
        req_id = req.get("requirement_id", "")
        title = req.get("title", "")
        priority = req.get("priority", "MEDIUM")
        ai_status = req.get("ai_status", "UNKNOWN")
        reasoning = req.get("reasoning", "")
        citations = req.get("evidence_citations", [])
        override = req.get("auditor_override")
        source_ref = req.get("source_reference", "")

        status_colors_map = {
            "SATISFIED": ("#059669", "#ecfdf5", "#a7f3d0"),
            "MISSING": ("#dc2626", "#fef2f2", "#fecaca"),
            "CONFLICT": ("#7c3aed", "#f5f3ff", "#ddd6fe"),
            "PARTIAL": ("#d97706", "#fffbeb", "#fde68a"),
        }
        status_color, status_bg, status_border = status_colors_map.get(
            ai_status, ("#475569", "#f8fafc", "#cbd5e1")
        )

        header_html = (
            f"<b>{req_id}</b>: {title} "
            f"<font color='#64748b' size='8'>[{priority}]</font>"
        )
        if source_ref:
            header_html += f" <font color='#94a3b8' size='7.5'>• Ref: {source_ref}</font>"

        status_pill = f"<font color='{status_color}'><b>{ai_status}</b></font>"

        citation_paragraphs = []
        if citations:
            for cit in citations:
                doc_name = cit.get("document_name", "Evidence Document")
                page = f"p. {cit.get('page_number')}" if cit.get("page_number") else ""
                sec = cit.get("section") or ""
                loc = " • ".join([x for x in [doc_name, page, sec] if x])
                quote = cit.get("quote", "").strip()

                citation_html = (
                    f"<b>Source:</b> <font color='#2563eb'>{loc}</font><br/>"
                    f"<i>&ldquo;{quote}&rdquo;</i>"
                )
                if cit.get("relevance"):
                    citation_html += f"<br/><font color='#475569' size='8'>Relevance: {cit.get('relevance')}</font>"

                citation_paragraphs.append(Paragraph(citation_html, styles["CitationBox"]))
        elif ai_status == "MISSING":
            citation_paragraphs.append(Paragraph(
                "<i>No verifiable evidence found in the uploaded submission artifacts.</i>",
                styles["NormalSmall"]
            ))

        override_html = ""
        if override:
            override_html = (
                f"<font color='#2563eb'><b>HUMAN AUDITOR OVERRIDE:</b></font> "
                f"Status adjusted from <b>{override.get('original_ai_status')}</b> to "
                f"<font color='#059669'><b>{override.get('overridden_status')}</b></font><br/>"
                f"<b>Reason:</b> {override.get('auditor_reason', '')}"
            )
            if override.get("auditor_note"):
                override_html += f"<br/><b>Note:</b> {override.get('auditor_note')}"

        card_content = [
            [
                Paragraph(header_html, styles["ReqTitle"]),
                Paragraph(status_pill, styles["ReqStatusBadge"]),
            ],
            [
                Paragraph(f"<b>AI Finding:</b> {reasoning}", styles["NormalSmall"]),
                "",
            ],
        ]

        for cp in citation_paragraphs:
            card_content.append([cp, ""])

        if override_html:
            card_content.append([Paragraph(override_html, styles["OverrideBox"]), ""])

        card_table = Table(card_content, colWidths=[6.2 * inch, 1.3 * inch])
        card_table.setStyle(TableStyle([
            ("SPAN", (0, 1), (1, 1)),
            ("SPAN", (0, 2), (1, 2)) if len(card_content) > 2 else ("NOP", (0, 0), (0, 0)),
            ("SPAN", (0, 3), (1, 3)) if len(card_content) > 3 else ("NOP", (0, 0), (0, 0)),
            ("SPAN", (0, 4), (1, 4)) if len(card_content) > 4 else ("NOP", (0, 0), (0, 0)),
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#ffffff")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor(status_border)),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        return card_table

    def _render_conflict_card(self, conf: Dict[str, Any], styles: Dict[str, ParagraphStyle]) -> Table:
        fact_label = conf.get("fact_label") or conf.get("fact", "Factual Contradiction")
        req_id = conf.get("related_requirement_id", "")
        src_a = conf.get("source_a", {})
        src_b = conf.get("source_b", {})
        explanation = conf.get("explanation", "")
        rec_action = conf.get("recommended_action", "")

        cit_a = src_a.get("citation", {}) if isinstance(src_a, dict) else {}
        cit_b = src_b.get("citation", {}) if isinstance(src_b, dict) else {}
        val_a = src_a.get("value", "") if isinstance(src_a, dict) else ""
        val_b = src_b.get("value", "") if isinstance(src_b, dict) else ""
        doc_a = sanitize_filename(cit_a.get("document_name", "Source A"))
        doc_b = sanitize_filename(cit_b.get("document_name", "Source B"))

        comp_html_a = (
            f"<b>Source A:</b> <font color='#2563eb'>{doc_a}</font><br/>"
            f"<b>Extracted Value:</b> <font color='#dc2626'><b>{val_a}</b></font><br/>"
            f"<i>&ldquo;{cit_a.get('quote', '')}&rdquo;</i>"
        )
        comp_html_b = (
            f"<b>Source B:</b> <font color='#2563eb'>{doc_b}</font><br/>"
            f"<b>Extracted Value:</b> <font color='#dc2626'><b>{val_b}</b></font><br/>"
            f"<i>&ldquo;{cit_b.get('quote', '')}&rdquo;</i>"
        )

        card_data = [
            [
                Paragraph(f"<b>Conflict on {fact_label}</b> ({req_id})", styles["ReqTitle"]),
                Paragraph("<font color='#7c3aed'><b>CONFLICT</b></font>", styles["ReqStatusBadge"]),
            ],
            [
                Paragraph(comp_html_a, styles["CitationBox"]),
                Paragraph(comp_html_b, styles["CitationBox"]),
            ],
            [
                Paragraph(f"<b>Discrepancy:</b> {explanation}<br/><b>Resolution Action:</b> {rec_action}", styles["NormalSmall"]),
                "",
            ],
        ]

        table = Table(card_data, colWidths=[3.75 * inch, 3.75 * inch])
        table.setStyle(TableStyle([
            ("SPAN", (0, 0), (0, 0)),
            ("SPAN", (0, 2), (1, 2)),
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#faf5ff")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#ddd6fe")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        return table

    def _build_styles(self) -> Dict[str, ParagraphStyle]:
        base_styles = getSampleStyleSheet()
        styles: Dict[str, ParagraphStyle] = {}

        styles["BrandTitle"] = ParagraphStyle(
            "BrandTitle",
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#0f172a"),
            spaceAfter=2,
        )

        styles["ReportSubtitle"] = ParagraphStyle(
            "ReportSubtitle",
            fontName="Helvetica",
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#475569"),
            spaceAfter=6,
        )

        styles["SectionHeader"] = ParagraphStyle(
            "SectionHeader",
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=15,
            textColor=colors.HexColor("#1e293b"),
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True,
        )

        styles["MetaKey"] = ParagraphStyle(
            "MetaKey",
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#334155"),
        )

        styles["MetaVal"] = ParagraphStyle(
            "MetaVal",
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#0f172a"),
        )

        styles["VerdictBox"] = ParagraphStyle(
            "VerdictBox",
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            alignment=1,
        )

        styles["NormalSmall"] = ParagraphStyle(
            "NormalSmall",
            fontName="Helvetica",
            fontSize=8.5,
            leading=11.5,
            textColor=colors.HexColor("#1e293b"),
        )

        styles["MutedNote"] = ParagraphStyle(
            "MutedNote",
            fontName="Helvetica",
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor("#64748b"),
        )

        styles["TableHead"] = ParagraphStyle(
            "TableHead",
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#1e293b"),
        )

        styles["ReqTitle"] = ParagraphStyle(
            "ReqTitle",
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#0f172a"),
        )

        styles["ReqStatusBadge"] = ParagraphStyle(
            "ReqStatusBadge",
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            alignment=2,
        )

        styles["CitationBox"] = ParagraphStyle(
            "CitationBox",
            fontName="Helvetica",
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor("#334155"),
            spaceBefore=2,
            spaceAfter=2,
        )

        styles["OverrideBox"] = ParagraphStyle(
            "OverrideBox",
            fontName="Helvetica",
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor("#1e3a8a"),
            spaceBefore=2,
            spaceAfter=2,
        )

        return styles

    @staticmethod
    def _format_date(iso_str: Optional[str]) -> str:
        if not iso_str:
            return "—"
        try:
            dt = datetime.fromisoformat(iso_str.replace("Z", "+00:00"))
            return dt.strftime("%Y-%m-%d %H:%M UTC")
        except Exception:
            return str(iso_str)


_report_service: Optional[ReportService] = None


def get_report_service() -> ReportService:
    global _report_service
    if _report_service is None:
        _report_service = ReportService()
    return _report_service
